In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from datasets import load_dataset

ds = load_dataset("Krishnan15/Personal_FinanceDataset")
print(ds)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
,The secret `HF_TOKEN` does not exist in your Colab secrets.
,To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
,You will be able to reuse this secret in all of your notebooks.
,Please note that authentication is recommended but still optional to access public models or datasets.
,  warnings.warn(
,Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
,WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(…)rsonal_finance_dataset_8000_extended.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/8000 [00:00<?, ? examples/s]

DatasetDict({
,    train: Dataset({
,        features: ['Date', 'Description', 'Amount', 'Category', 'PaymentMethod', 'Location', 'AccountType', 'TransactionType', 'DeviceUsed', 'Currency', 'MerchantType', 'LoyaltyProgram', 'Weekday', 'Month', 'TimeOfDay'],
,        num_rows: 8000
,    })
,})

In [ ]:
pf = ds['train'].to_pandas()
pf.head()

,Date,Description,Amount,Category,PaymentMethod,Location,AccountType,TransactionType,DeviceUsed,Currency,MerchantType,LoyaltyProgram,Weekday,Month,TimeOfDay
0,2025-04-05,Transaction at IRCTC,20666.49,Travel,Debit Card,Kolkata,Salary,Debit,Mobile,INR,Service,No,Saturday,April,Night
1,2025-12-06,Transaction at Myntra,1919.05,Online Shopping,Net Banking,Hyderabad,Salary,Debit,Desktop,INR,Online Store,Yes,Saturday,December,Evening
2,2025-06-20,Transaction at BigBazaar,2837.68,Grocery,Debit Card,Bangalore,Savings,Debit,Mobile,INR,Retail,No,Friday,June,Evening
3,2025-04-23,Transaction at Property Tax Online,1071.04,Bills,Net Banking,Delhi,Current,Debit,POS Terminal,INR,Service,Yes,Wednesday,April,Afternoon
4,2025-03-06,Transaction at Asus Store,10722.80,Electronics,Debit Card,Mumbai,Current,Debit,Mobile,INR,Retail,Yes,Thursday,March,Evening

In [ ]:
print(pf.columns)

Index(['Date', 'Description', 'Amount', 'Category', 'PaymentMethod',
,       'Location', 'AccountType', 'TransactionType', 'DeviceUsed', 'Currency',
,       'MerchantType', 'LoyaltyProgram', 'Weekday', 'Month', 'TimeOfDay'],
,      dtype='object')

In [ ]:
#total spent over each category
pf.groupby('Category')['Amount'].sum()

Category
Bills               2403511.15
Clothing            3265835.78
Electronics        61863867.55
Entertainment        459321.53
Food                 649145.95
Grocery             2036452.10
Healthcare          8586057.88
Online Shopping     8118349.93
Transport            818746.49
Travel             12214347.67
Name: Amount, dtype: float64

In [ ]:
#total spent over date
pf.groupby('Date')['Amount'].sum()

Date
2025-01-01    296956.65
2025-01-02     96903.60
2025-01-03    203710.83
2025-01-04    236549.88
2025-01-05     96069.13
                ...
2025-12-27    241593.98
2025-12-28    349178.34
2025-12-29    363930.54
2025-12-30    186213.65
2025-12-31    450399.94
Name: Amount, Length: 365, dtype: float64

In [ ]:
#total spent over each month
pf.groupby('Month')['Amount'].sum()

Month
April        7937485.11
August       8692664.18
December     8391272.78
February     7327831.77
January      8093666.23
July         8951073.24
June         9018844.54
March        9390091.29
May          8847821.63
November     8039843.94
October      7022232.93
September    8702808.39
Name: Amount, dtype: float64

In [ ]:
pf.isnull().sum()

Date               0
Description        0
Amount             0
Category           0
PaymentMethod      0
Location           0
AccountType        0
TransactionType    0
DeviceUsed         0
Currency           0
MerchantType       0
LoyaltyProgram     0
Weekday            0
Month              0
TimeOfDay          0
dtype: int64

In [ ]:
#conversion to csv for database and python to use
pf.to_csv('finance_closed',index='false')